name: Update badges

on:
  schedule:
    # Runs at 12am UTC every month
    - cron: " 0 0 1 * *"
  workflow_dispatch: # Permet de déclencher manuellement le workflow
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update badges in README
        uses: pemtajo/badge-readme@main
        with:
          COMMIT_MESSAGE: "Badges updated" # optional
          CREDLY_USER: tanguy-frageul # optional, but default will use the same from github
          CREDLY_SORT: RECENT # optional, this is the two forms from credly sort, more popular or recent first, by default use RECENT
          NUMBER_LAST_BADGES: 0
